# 2022 Data Cleanse:

In [1]:
# Import the dependencies.

import pandas as pd
import numpy as np

In [2]:
# Files to read from:

data_2022 = "Resources/JC-202201-citibike-tripdata.csv"

In [3]:
# Create 2022 Data Frame.

data_2022_df = pd.read_csv(data_2022)

In [4]:
# Remove unwanted columns:

del data_2022_df["ride_id"]
del data_2022_df["rideable_type"]
del data_2022_df["start_station_id"]
del data_2022_df["end_station_id"]

In [5]:
# Replace values within dataframe:

data_2022_df['member_casual'].replace('member','Member', inplace=True)
data_2022_df['member_casual'].replace('casual','Casual', inplace=True)

In [6]:
# Rename columns:

cleaned_2022_df=data_2022_df.rename(columns={"started_at":"Start_Time", "ended_at":"End_Time", "start_station_name":"Start_Station", "end_station_name":"End_Station", "start_lat":"Start_LAT", "start_lng":"Start_LON", "end_lat":"End_LAT", "end_lng":"End_LON", "member_casual":"Client_Type"})

In [7]:
# Change times from string (object) to timedelta64 format: 

cleaned_2022_df['Start_Time']=pd.to_datetime(cleaned_2022_df.Start_Time)
cleaned_2022_df['End_Time']=pd.to_datetime(cleaned_2022_df.End_Time)

In [8]:
# Calculate the duration of bike hire:

cleaned_2022_df['Duration(sec)']=(cleaned_2022_df.End_Time-cleaned_2022_df.Start_Time).astype('timedelta64[s]')
cleaned_2022_df['Duration(sec)']=cleaned_2022_df['Duration(sec)'].astype(int)

In [9]:
# Determine the starting hour and day of week. (Note Monday=0 and Sunday=6):

cleaned_2022_df["Hour_Start"]=cleaned_2022_df.Start_Time.dt.hour
cleaned_2022_df["Day_Start"]=cleaned_2022_df.Start_Time.dt.dayofweek

In [10]:
# Write if statement to determine if loans took place during peak hours:

conditions=[(cleaned_2022_df["Hour_Start"]>=8) & (cleaned_2022_df["Hour_Start"]<=10) & (cleaned_2022_df["Day_Start"]>=0) & (cleaned_2022_df["Day_Start"]<=4),(cleaned_2022_df["Hour_Start"]>=16) & (cleaned_2022_df["Hour_Start"]<=18) & (cleaned_2022_df["Day_Start"]>=0) & (cleaned_2022_df["Day_Start"]<=4)]
choices=["AM_Peak", "PM_Peak"]
cleaned_2022_df["Peak"]=np.select(conditions, choices, default="Off_Peak")

In [11]:
# Re-order the columns:

cleaned_2022_df=cleaned_2022_df[["Start_Time", "Hour_Start", "Day_Start", "Peak", "End_Time", "Duration(sec)", "Start_LAT", "Start_LON", "Start_Station", "End_LAT", "End_LON", "End_Station", "Client_Type"]]

In [12]:
# Remove rows with missing value(s):

cleaned_2022_df=cleaned_2022_df.dropna(how='any')

In [13]:
cleaned_2022_df

,Start_Time,Hour_Start,Day_Start,Peak,End_Time,Duration(sec),Start_LAT,Start_LON,Start_Station,End_LAT,End_LON,End_Station,Client_Type
0,2022-01-26 18:50:39,18,2,PM_Peak,2022-01-26 18:51:53,74,40.750604,-74.024020,12 St & Sinatra Dr N,40.750604,-74.024020,12 St & Sinatra Dr N,Member
1,2022-01-28 13:14:07,13,4,Off_Peak,2022-01-28 13:20:23,376,40.712774,-74.036486,Essex Light Rail,40.712774,-74.036486,Essex Light Rail,Member
2,2022-01-10 19:55:13,19,0,Off_Peak,2022-01-10 20:00:37,324,40.712774,-74.036486,Essex Light Rail,40.712774,-74.036486,Essex Light Rail,Member
3,2022-01-26 07:54:57,7,2,Off_Peak,2022-01-26 07:55:22,25,40.750604,-74.024020,12 St & Sinatra Dr N,40.750604,-74.024020,12 St & Sinatra Dr N,Member
4,2022-01-13 18:44:46,18,3,PM_Peak,2022-01-13 18:45:43,57,40.750604,-74.024020,12 St & Sinatra Dr N,40.750604,-74.024020,12 St & Sinatra Dr N,Member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
26757,2022-01-03 16:07:27,16,0,PM_Peak,2022-01-03 16:12:05,278,40.745910,-74.057271,Leonard Gordon Park,40.733670,-74.062500,Journal Square,Member
26758,2022-01-22 20:02:58,20,5,Off_Peak,2022-01-22 20:07:32,274,40.745910,-74.057271,Leonard Gordon Park,40.733670,-74.062500,Journal Square,Member
26759,2022-01-26 12:35:21,12,2,Off_Peak,2022-01-26 12:44:00,519,40.745910,-74.057271,Leonard Gordon Park,40.733670,-74.062500,Journal Square,Member
26760,2022-01-28 12:56:34,12,4,Off_Peak,2022-01-28 13:06:45,611,40.745910,-74.057271,Leonard Gordon Park,40.733670,-74.062500,Journal Square,Member
26761,2022-01-31 12:45:16,12,0,Off_Peak,2022-01-31 12:52:05,409,40.745910,-74.057271,Leonard Gordon Park,40.733670,-74.062500,Journal Square,Member

# 2021 Data Cleanse:

In [14]:
# Files to read from:

data_2021 = "Resources/JC-202101-citibike-tripdata.csv"

In [15]:
# Create 2022 Data Frame.

data_2021_df = pd.read_csv(data_2021)

In [16]:
# Remove unwanted columns:

del data_2021_df["gender"]
del data_2021_df["birth year"]
del data_2021_df["start station id"]
del data_2021_df["end station id"]
del data_2021_df["bikeid"]

In [17]:
# Replace values within dataframe:

data_2021_df['usertype'].replace('Subscriber','Member', inplace=True)
data_2021_df['usertype'].replace('Customer','Casual', inplace=True)

In [18]:
# Rename columns:

cleaned_2021_df=data_2021_df.rename(columns={"tripduration":"Duration(sec)", "starttime":"Start_Time", "stoptime":"End_Time", "start station name":"Start_Station", "end station name":"End_Station", "start station latitude":"Start_LAT", "start station longitude":"Start_LON", "end station latitude":"End_LAT", "end station longitude":"End_LON", "usertype":"Client_Type"})

In [19]:
# Change times from string (object) to timedelta64 format: 

cleaned_2021_df['Start_Time']=pd.to_datetime(cleaned_2021_df.Start_Time)
cleaned_2021_df['End_Time']=pd.to_datetime(cleaned_2021_df.End_Time)

In [20]:
# Determine the starting hour and day of week. (Note Monday=0 and Sunday=6):

cleaned_2021_df["Hour_Start"]=cleaned_2021_df.Start_Time.dt.hour
cleaned_2021_df["Day_Start"]=cleaned_2021_df.Start_Time.dt.dayofweek

In [21]:
# Write if statement to determine if loans took place during peak hours:

conditions=[(cleaned_2021_df["Hour_Start"]>=8) & (cleaned_2021_df["Hour_Start"]<=10) & (cleaned_2021_df["Day_Start"]>=0) & (cleaned_2021_df["Day_Start"]<=4),(cleaned_2021_df["Hour_Start"]>=16) & (cleaned_2021_df["Hour_Start"]<=18) & (cleaned_2021_df["Day_Start"]>=0) & (cleaned_2021_df["Day_Start"]<=4)]
choices=["AM_Peak", "PM_Peak"]
cleaned_2021_df["Peak"]=np.select(conditions, choices, default="Off_Peak")

In [22]:
# Re-order the columns:

cleaned_2021_df=cleaned_2021_df[["Start_Time", "Hour_Start", "Day_Start", "Peak", "End_Time", "Duration(sec)", "Start_LAT", "Start_LON", "Start_Station", "End_LAT", "End_LON", "End_Station", "Client_Type"]]

In [23]:
# Remove rows with missing value(s):

cleaned_2021_df=cleaned_2021_df.dropna(how='any')

In [24]:
cleaned_2021_df

,Start_Time,Hour_Start,Day_Start,Peak,End_Time,Duration(sec),Start_LAT,Start_LON,Start_Station,End_LAT,End_LON,End_Station,Client_Type
0,2021-01-01 00:03:35.510,0,4,Off_Peak,2021-01-01 00:08:01.777,266,40.721651,-74.042884,Manila & 1st,40.724176,-74.050656,Brunswick St,Member
1,2021-01-01 00:23:32.925,0,4,Off_Peak,2021-01-01 00:49:16.083,1543,40.715178,-74.037683,Grand St,40.718489,-74.047727,Van Vorst Park,Casual
2,2021-01-01 00:23:50.794,0,4,Off_Peak,2021-01-01 00:48:12.566,1461,40.715178,-74.037683,Grand St,40.718489,-74.047727,Van Vorst Park,Casual
3,2021-01-01 00:31:09.077,0,4,Off_Peak,2021-01-01 00:44:22.943,793,40.717732,-74.043845,City Hall,40.728745,-74.032108,Newport Pkwy,Casual
4,2021-01-01 00:35:52.190,0,4,Off_Peak,2021-01-01 00:45:48.774,596,40.719252,-74.034234,Harborside,40.724176,-74.050656,Brunswick St,Casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11619,2021-01-31 20:16:05.470,20,6,Off_Peak,2021-01-31 20:57:22.011,2476,40.721124,-74.038051,Warren St,40.719420,-74.050990,Montgomery St,Member
11620,2021-01-31 21:05:05.209,21,6,Off_Peak,2021-01-31 21:07:32.866,147,40.719586,-74.043117,Grove St PATH,40.721124,-74.038051,Warren St,Member
11621,2021-01-31 21:06:23.588,21,6,Off_Peak,2021-01-31 21:17:23.842,660,40.721525,-74.046305,Newark Ave,40.714584,-74.042817,Marin Light Rail,Member
11622,2021-01-31 21:16:37.822,21,6,Off_Peak,2021-01-31 21:23:02.124,384,40.716540,-74.049638,JC Medical Center,40.713464,-74.062859,Lafayette Park,Member
11623,2021-01-31 23:24:50.881,23,6,Off_Peak,2021-01-31 23:30:47.303,356,40.719252,-74.034234,Harborside,40.719586,-74.043117,Grove St PATH,Member

# 2020 Data Cleanse:

In [25]:
# Files to read from:

data_2020 = "Resources/JC-202001-citibike-tripdata.csv"

In [26]:
# Create 2022 Data Frame.

data_2020_df = pd.read_csv(data_2020)

In [27]:
# Remove unwanted columns:

del data_2020_df["gender"]
del data_2020_df["birth year"]
del data_2020_df["start station id"]
del data_2020_df["end station id"]
del data_2020_df["bikeid"]

In [28]:
# Replace values within dataframe:

data_2020_df['usertype'].replace('Subscriber','Member', inplace=True)
data_2020_df['usertype'].replace('Customer','Casual', inplace=True)

In [29]:
# Rename columns:

cleaned_2020_df=data_2020_df.rename(columns={"tripduration":"Duration(sec)", "starttime":"Start_Time", "stoptime":"End_Time", "start station name":"Start_Station", "end station name":"End_Station", "start station latitude":"Start_LAT", "start station longitude":"Start_LON", "end station latitude":"End_LAT", "end station longitude":"End_LON", "usertype":"Client_Type"})

In [30]:
# Change times from string (object) to timedelta64 format: 

cleaned_2020_df['Start_Time']=pd.to_datetime(cleaned_2020_df.Start_Time)
cleaned_2020_df['End_Time']=pd.to_datetime(cleaned_2020_df.End_Time)

In [31]:
# Determine the starting hour and day of week. (Note Monday=0 and Sunday=6):

cleaned_2020_df["Hour_Start"]=cleaned_2020_df.Start_Time.dt.hour
cleaned_2020_df["Day_Start"]=cleaned_2020_df.Start_Time.dt.dayofweek

In [32]:
# Write if statement to determine if loans took place during peak hours:

conditions=[(cleaned_2020_df["Hour_Start"]>=8) & (cleaned_2020_df["Hour_Start"]<=10) & (cleaned_2020_df["Day_Start"]>=0) & (cleaned_2020_df["Day_Start"]<=4),(cleaned_2020_df["Hour_Start"]>=16) & (cleaned_2020_df["Hour_Start"]<=18) & (cleaned_2020_df["Day_Start"]>=0) & (cleaned_2020_df["Day_Start"]<=4)]
choices=["AM_Peak", "PM_Peak"]
cleaned_2020_df["Peak"]=np.select(conditions, choices, default="Off_Peak")

In [33]:
# Re-order the columns:

cleaned_2020_df=cleaned_2020_df[["Start_Time", "Hour_Start", "Day_Start", "Peak", "End_Time", "Duration(sec)", "Start_LAT", "Start_LON", "Start_Station", "End_LAT", "End_LON", "End_Station", "Client_Type"]]

In [34]:
# Remove rows with missing value(s):

cleaned_2020_df=cleaned_2020_df.dropna(how='any')

In [35]:
cleaned_2020_df

,Start_Time,Hour_Start,Day_Start,Peak,End_Time,Duration(sec),Start_LAT,Start_LON,Start_Station,End_LAT,End_LON,End_Station,Client_Type
0,2020-01-01 00:04:50.192,0,2,Off_Peak,2020-01-01 00:08:37.037,226,40.719586,-74.043117,Grove St PATH,40.721525,-74.046305,Newark Ave,Member
1,2020-01-01 00:16:01.670,0,2,Off_Peak,2020-01-01 00:22:19.080,377,40.719586,-74.043117,Grove St PATH,40.726012,-74.050389,Brunswick & 6th,Member
2,2020-01-01 00:17:33.877,0,2,Off_Peak,2020-01-01 00:22:22.442,288,40.719586,-74.043117,Grove St PATH,40.726012,-74.050389,Brunswick & 6th,Casual
3,2020-01-01 00:32:05.902,0,2,Off_Peak,2020-01-01 00:39:21.066,435,40.730897,-74.063913,Sip Ave,40.719282,-74.071262,Astor Place,Casual
4,2020-01-01 00:46:19.678,0,2,Off_Peak,2020-01-01 00:50:11.344,231,40.719586,-74.043117,Grove St PATH,40.714584,-74.042817,Marin Light Rail,Member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
26015,2020-01-31 23:29:29.391,23,4,Off_Peak,2020-01-31 23:38:33.691,544,40.718489,-74.047727,Van Vorst Park,40.725340,-74.067622,McGinley Square,Member
26016,2020-01-31 23:30:59.367,23,4,Off_Peak,2020-01-31 23:33:01.687,122,40.716870,-74.032810,Columbus Dr at Exchange Pl,40.719252,-74.034234,Harborside,Member
26017,2020-01-31 23:42:34.846,23,4,Off_Peak,2020-01-31 23:45:55.878,201,40.721651,-74.042884,Manila & 1st,40.724176,-74.050656,Brunswick St,Member
26018,2020-01-31 23:45:00.680,23,4,Off_Peak,2020-01-31 23:50:00.874,300,40.717732,-74.043845,City Hall,40.712419,-74.038526,Morris Canal,Member
26019,2020-01-31 23:48:35.170,23,4,Off_Peak,2020-02-01 00:00:36.406,721,40.731169,-74.057574,Hilltop,40.727224,-74.033759,Newport PATH,Casual

# 2019 Data Cleanse:

In [36]:
# Files to read from:

data_2019 = "Resources/JC-201901-citibike-tripdata.csv"

In [37]:
# Create 2022 Data Frame.

data_2019_df = pd.read_csv(data_2019)

In [38]:
# Remove unwanted columns:

del data_2019_df["gender"]
del data_2019_df["birth year"]
del data_2019_df["start station id"]
del data_2019_df["end station id"]
del data_2019_df["bikeid"]

In [39]:
# Replace values within dataframe:

data_2019_df['usertype'].replace('Subscriber','Member', inplace=True)
data_2019_df['usertype'].replace('Customer','Casual', inplace=True)

In [40]:
# Rename columns:

cleaned_2019_df=data_2019_df.rename(columns={"tripduration":"Duration(sec)", "starttime":"Start_Time", "stoptime":"End_Time", "start station name":"Start_Station", "end station name":"End_Station", "start station latitude":"Start_LAT", "start station longitude":"Start_LON", "end station latitude":"End_LAT", "end station longitude":"End_LON", "usertype":"Client_Type"})

In [41]:
# Change times from string (object) to timedelta64 format: 

cleaned_2019_df['Start_Time']=pd.to_datetime(cleaned_2019_df.Start_Time)
cleaned_2019_df['End_Time']=pd.to_datetime(cleaned_2019_df.End_Time)

In [42]:
# Determine the starting hour and day of week. (Note Monday=0 and Sunday=6):

cleaned_2019_df["Hour_Start"]=cleaned_2019_df.Start_Time.dt.hour
cleaned_2019_df["Day_Start"]=cleaned_2019_df.Start_Time.dt.dayofweek

In [43]:
# Write if statement to determine if loans took place during peak hours:

conditions=[(cleaned_2019_df["Hour_Start"]>=8) & (cleaned_2019_df["Hour_Start"]<=10) & (cleaned_2019_df["Day_Start"]>=0) & (cleaned_2019_df["Day_Start"]<=4),(cleaned_2019_df["Hour_Start"]>=16) & (cleaned_2019_df["Hour_Start"]<=18) & (cleaned_2019_df["Day_Start"]>=0) & (cleaned_2019_df["Day_Start"]<=4)]
choices=["AM_Peak", "PM_Peak"]
cleaned_2019_df["Peak"]=np.select(conditions, choices, default="Off_Peak")

In [44]:
# Re-order the columns:

cleaned_2019_df=cleaned_2019_df[["Start_Time", "Hour_Start", "Day_Start", "Peak", "End_Time", "Duration(sec)", "Start_LAT", "Start_LON", "Start_Station", "End_LAT", "End_LON", "End_Station", "Client_Type"]]

In [45]:
# Remove rows with missing value(s):

cleaned_2019_df=cleaned_2019_df.dropna(how='any')

In [46]:
cleaned_2019_df

,Start_Time,Hour_Start,Day_Start,Peak,End_Time,Duration(sec),Start_LAT,Start_LON,Start_Station,End_LAT,End_LON,End_Station,Client_Type
0,2019-01-01 03:09:09.711,3,1,Off_Peak,2019-01-01 03:12:30.879,201,40.716247,-74.033459,Exchange Place,40.712774,-74.036486,Essex Light Rail,Member
1,2019-01-01 05:18:00.106,5,1,Off_Peak,2019-01-01 05:26:25.905,505,40.716247,-74.033459,Exchange Place,40.724294,-74.035483,Washington St,Member
2,2019-01-01 10:36:33.340,10,1,AM_Peak,2019-01-01 10:49:10.260,756,40.716247,-74.033459,Exchange Place,40.711242,-74.055701,Liberty Light Rail,Member
3,2019-01-01 12:43:38.643,12,1,Off_Peak,2019-01-01 13:09:54.528,1575,40.716247,-74.033459,Exchange Place,40.724294,-74.035483,Washington St,Casual
4,2019-01-01 12:43:39.601,12,1,Off_Peak,2019-01-01 13:09:46.510,1566,40.716247,-74.033459,Exchange Place,40.724294,-74.035483,Washington St,Casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19671,2019-01-26 06:40:17.332,6,5,Off_Peak,2019-01-26 06:54:30.888,853,40.711130,-74.078900,Jackson Square,40.716247,-74.033459,Exchange Place,Member
19672,2019-01-27 06:36:20.640,6,6,Off_Peak,2019-01-27 06:51:57.146,936,40.711130,-74.078900,Jackson Square,40.716247,-74.033459,Exchange Place,Member
19673,2019-01-27 21:14:08.546,21,6,Off_Peak,2019-01-27 21:25:01.617,653,40.711130,-74.078900,Jackson Square,40.727551,-74.071061,Glenwood Ave,Casual
19674,2019-01-29 06:15:26.588,6,1,Off_Peak,2019-01-29 06:31:26.730,960,40.711130,-74.078900,Jackson Square,40.716247,-74.033459,Exchange Place,Member
19675,2019-01-30 06:30:03.605,6,2,Off_Peak,2019-01-30 06:48:33.276,1109,40.711130,-74.078900,Jackson Square,40.716247,-74.033459,Exchange Place,Member

In [47]:
combined_df=pd.concat([cleaned_2019_df, cleaned_2020_df, cleaned_2021_df, cleaned_2022_df])

In [50]:
combined_df.to_csv('Combined_Data.csv', index=False)